<?php

$_COS_LANG_MODULE['You are logged in using email: '] = 'Du er logget ind via e-mail:';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Din screenname er ikke indstillet endnu';
$_COS_LANG_MODULE['Your screenname is: '] = 'Dit screenname er:';
$_COS_LANG_MODULE['Logout'] = 'Log af';
$_COS_LANG_MODULE['Submitted by: '] = 'Indsendt af:';
$_COS_LANG_MODULE['User'] = 'Bruger';
$_COS_LANG_MODULE['Profile page '] = 'Profilside';
$_COS_LANG_MODULE['This is your profile.'] = 'Dette er din profil.';
$_COS_LANG_MODULE['No bio yet'] = 'Nr bio endnu';
$_COS_LANG_MODULE['Your profile'] = 'Din profil';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Din profil er tom!';
$_COS_LANG_MODULE['Screen name'] = 'Screen navn';
$_COS_LANG_MODULE['Website'] = 'Websted';
$_COS_LANG_MODULE['No website'] = 'Ingen hjemmeside';
$_COS_LANG_MODULE['Unknown'] = 'Ukendt';
$_COS_LANG_MODULE['Age'] = 'Alder';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Din profil er blevet opdateret';
$_COS_LANG_MODULE['Not a valid website'] = 'Ikke en gyldig website';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Ikke en gyldig fødselsdag';
$_COS_LANG_MODULE['You are not that old'] = 'Du er ikke så gammel';
$_COS_LANG_MODULE['Edit your profile information'] = 'Rediger dine profiloplysninger';
$_COS_LANG_MODULE['Your website'] = 'Dit websted';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Din fødselsdag. Format er yyyy-mm-dd';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Skriv et par ord om dig selv';
$_COS_LANG_MODULE['Update'] = 'Opdatering';
