<?php

$_COS_LANG_MODULE['You are logged in using email: '] = '您登录使用电子邮件：';
$_COS_LANG_MODULE['Your screenname is not set yet'] = '你的屏幕名尚未设定';
$_COS_LANG_MODULE['Your screenname is: '] = '你的屏幕名是：';
$_COS_LANG_MODULE['Logout'] = '注销';
$_COS_LANG_MODULE['Submitted by: '] = '提交者：';
$_COS_LANG_MODULE['User'] = '用户';
$_COS_LANG_MODULE['Profile page '] = '个人资料页';
$_COS_LANG_MODULE['This is your profile.'] = '这是您的个人资料。';
$_COS_LANG_MODULE['No bio yet'] = '无生物还';
$_COS_LANG_MODULE['Your profile'] = '您的个人资料';
$_COS_LANG_MODULE['Your profile is empty!'] = '您的个人资料是空的！';
$_COS_LANG_MODULE['Screen name'] = '屏幕名称';
$_COS_LANG_MODULE['Website'] = '网站';
$_COS_LANG_MODULE['No website'] = '没有网站';
$_COS_LANG_MODULE['Unknown'] = '未知';
$_COS_LANG_MODULE['Age'] = '年龄';
$_COS_LANG_MODULE['Your profile has been updated'] = '您的个人资料已更新';
$_COS_LANG_MODULE['Not a valid website'] = '没有一个有效的网站';
$_COS_LANG_MODULE['Not a valid birthday'] = '不是一个有效的生日';
$_COS_LANG_MODULE['You are not that old'] = '你是不是老';
$_COS_LANG_MODULE['Edit your profile information'] = '编辑您的个人资料信息';
$_COS_LANG_MODULE['Your website'] = '您的网站';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = '你的生日。格式为YYYY-MM-DD';
$_COS_LANG_MODULE['Write a few words about yourself'] = '写下自己的几句话';
$_COS_LANG_MODULE['Update'] = '更新';
