<?php


// Translation of file /modules/userinfo/views.php

$_COS_LANG_MODULE['No such account'] = 'No such account';
$_COS_LANG_MODULE['Account Profile'] = 'Account Profile';
$_COS_LANG_MODULE['View user profile'] = 'View user profile';
$_COS_LANG_MODULE['Identicon image'] = 'Identicon image';
$_COS_LANG_MODULE['Screen name'] = 'Screen name';
$_COS_LANG_MODULE['Website'] = 'Website';
$_COS_LANG_MODULE['Profile name'] = 'Profile name';
$_COS_LANG_MODULE['Age'] = 'Age';
$_COS_LANG_MODULE['Profile Description'] = 'Profile Description';
$_COS_LANG_MODULE['You are this profile'] = 'You are this profile';
$_COS_LANG_MODULE['Edit profile'] = 'Edit profile';
$_COS_LANG_MODULE['Edit account profile'] = 'Edit account profile';
$_COS_LANG_MODULE['First name'] = 'First name';
$_COS_LANG_MODULE['Last name'] = 'Last name';
$_COS_LANG_MODULE['Email. <br />Will not be displayed to users. Will be used for gravatars if any is set for the email. <br />We may send you a mail with some important messages.'] = 'Email. <br />Will not be displayed to users. Will be used for gravatars if any is set for the email. <br />We may send you a mail with some important messages.';
$_COS_LANG_MODULE['Birthday. Format is: YYYY-MM-DD. Will only be used for displaying your age'] = 'Birthday. Format is: YYYY-MM-DD. Will only be used for displaying your age';
$_COS_LANG_MODULE['submit'] = 'submit';
$_COS_LANG_MODULE['Submitted by: '] = 'Submitted by: ';

// Translation of file /modules/userinfo/module.php

$_COS_LANG_MODULE['You are logged in using email: '] = 'You are logged in using email: ';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Your screenname is not set yet';
$_COS_LANG_MODULE['Your screenname is: '] = 'Your screenname is: ';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['User'] = 'User';
$_COS_LANG_MODULE['Profile page '] = 'Profile page ';
$_COS_LANG_MODULE['No bio yet'] = 'No bio yet';
$_COS_LANG_MODULE['Your profile'] = 'Your profile';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Your profile is empty!';
$_COS_LANG_MODULE['No website'] = 'No website';
$_COS_LANG_MODULE['Unknown'] = 'Unknown';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Your profile has been updated';
$_COS_LANG_MODULE['Not a valid website'] = 'Not a valid website';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Not a valid birthday';
$_COS_LANG_MODULE['Edit your profile information'] = 'Edit your profile information';
$_COS_LANG_MODULE['Your website'] = 'Your website';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Your birthday. Format is yyyy-mm-dd';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Write a few words about yourself';
$_COS_LANG_MODULE['Update'] = 'Update';
