<?php


// Translation of file /modules/userinfo/module.php

$_COS_LANG_MODULE['You are logged in using email: '] = 'You are logged in using email: ';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Your screenname is not set yet';
$_COS_LANG_MODULE['Your screenname is: '] = 'Your screenname is: ';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['Submitted by: '] = 'Submitted by: ';
$_COS_LANG_MODULE['User'] = 'User';
$_COS_LANG_MODULE['Profile page '] = 'Profile page ';
$_COS_LANG_MODULE['This is your profile.'] = 'This is your profile.';
$_COS_LANG_MODULE['No bio yet'] = 'No bio yet';
$_COS_LANG_MODULE['Your profile'] = 'Your profile';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Your profile is empty!';
$_COS_LANG_MODULE['Screen name'] = 'Screen name';
$_COS_LANG_MODULE['Website'] = 'Website';
$_COS_LANG_MODULE['No website'] = 'No website';
$_COS_LANG_MODULE['Unknown'] = 'Unknown';
$_COS_LANG_MODULE['Age'] = 'Age';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Your profile has been updated';
$_COS_LANG_MODULE['Not a valid website'] = 'Not a valid website';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Not a valid birthday';
$_COS_LANG_MODULE['You are not that old'] = 'You are not that old';
$_COS_LANG_MODULE['Edit your profile information'] = 'Edit your profile information';
$_COS_LANG_MODULE['Your website'] = 'Your website';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Your birthday. Format is yyyy-mm-dd';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Write a few words about yourself';
$_COS_LANG_MODULE['Update'] = 'Update';
