<?php

$_COS_LANG_MODULE['You are logged in using email: '] = 'Du er logget inn ved bruk av e-post:';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Din Screen er ikke satt ennå';
$_COS_LANG_MODULE['Your screenname is: '] = 'Din Screen er:';
$_COS_LANG_MODULE['Logout'] = 'Utlogging';
$_COS_LANG_MODULE['Submitted by: '] = 'Skrevet av:';
$_COS_LANG_MODULE['User'] = 'Bruker';
$_COS_LANG_MODULE['Profile page '] = 'Profilside';
$_COS_LANG_MODULE['This is your profile.'] = 'Dette er din profil.';
$_COS_LANG_MODULE['No bio yet'] = 'Ingen bio ennå';
$_COS_LANG_MODULE['Your profile'] = 'Profilen din';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Profilen din er tom!';
$_COS_LANG_MODULE['Screen name'] = 'Skjermnavn';
$_COS_LANG_MODULE['Website'] = 'Nettsted';
$_COS_LANG_MODULE['No website'] = 'Ingen nettside';
$_COS_LANG_MODULE['Unknown'] = 'Ukjent';
$_COS_LANG_MODULE['Age'] = 'Alder';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Profilen din er oppdatert';
$_COS_LANG_MODULE['Not a valid website'] = 'Ikke en gyldig nettside';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Ikke en gyldig bursdag';
$_COS_LANG_MODULE['You are not that old'] = 'Du er ikke så gammel';
$_COS_LANG_MODULE['Edit your profile information'] = 'Redigere profilinformasjonen';
$_COS_LANG_MODULE['Your website'] = 'Ditt nettsted';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Bursdagen din. Formatet er åååå-mm-dd';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Skriv noen ord om deg selv';
$_COS_LANG_MODULE['Update'] = 'Oppdatering';
