<?php

$_COS_LANG_MODULE['You are logged in using email: '] = 'Sie sind im Umgang mit E-Mail protokolliert:';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Ihr screenname steht noch nicht fest';
$_COS_LANG_MODULE['Your screenname is: '] = 'Ihr screen ist:';
$_COS_LANG_MODULE['Logout'] = 'Logout';
$_COS_LANG_MODULE['Submitted by: '] = 'Eingereicht:';
$_COS_LANG_MODULE['User'] = 'Benutzer';
$_COS_LANG_MODULE['Profile page '] = 'Profilseite';
$_COS_LANG_MODULE['This is your profile.'] = 'Dies ist Ihr Profil ab.';
$_COS_LANG_MODULE['No bio yet'] = 'Kein bio noch';
$_COS_LANG_MODULE['Your profile'] = 'Ihr Profil';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Ihr Profil ist leer!';
$_COS_LANG_MODULE['Screen name'] = 'Künstlername';
$_COS_LANG_MODULE['Website'] = 'Webseite';
$_COS_LANG_MODULE['No website'] = 'Keine Website';
$_COS_LANG_MODULE['Unknown'] = 'Unbekannt';
$_COS_LANG_MODULE['Age'] = 'Alter';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Ihr Profil wurde aktualisiert';
$_COS_LANG_MODULE['Not a valid website'] = 'Kein gültiges Website';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Keine gültige Geburtstag';
$_COS_LANG_MODULE['You are not that old'] = 'Sie sind nicht so alt';
$_COS_LANG_MODULE['Edit your profile information'] = 'Passen Sie Ihr Profil Informationen';
$_COS_LANG_MODULE['Your website'] = 'Ihre Website-';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Ihr Geburtstag. Format ist yyyy-mm-dd';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Schreiben Sie ein paar Worte über sich selbst';
$_COS_LANG_MODULE['Update'] = 'Aktualisierung';
