<?php

$_COS_LANG_MODULE['You are logged in using email: '] = 'Olet kirjautunut sisään sähköpostin:';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Sinun ScreenName ei ole vielä asetettu';
$_COS_LANG_MODULE['Your screenname is: '] = 'Sinun ScreenName on:';
$_COS_LANG_MODULE['Logout'] = 'Kirjaudu ulos';
$_COS_LANG_MODULE['Submitted by: '] = 'Lähettäjä:';
$_COS_LANG_MODULE['User'] = 'Käyttäjä';
$_COS_LANG_MODULE['Profile page '] = 'Profiili sivu';
$_COS_LANG_MODULE['This is your profile.'] = 'Tämä on profiiliisi.';
$_COS_LANG_MODULE['No bio yet'] = 'Ei bio vielä';
$_COS_LANG_MODULE['Your profile'] = 'Profiilisi';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Profiilisi on tyhjä!';
$_COS_LANG_MODULE['Screen name'] = 'Näytön nimi';
$_COS_LANG_MODULE['Website'] = 'Verkkosivusto';
$_COS_LANG_MODULE['No website'] = 'Ei verkkosivuilla';
$_COS_LANG_MODULE['Unknown'] = 'Tuntematon';
$_COS_LANG_MODULE['Age'] = 'Ikä';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Profiilisi on päivitetty';
$_COS_LANG_MODULE['Not a valid website'] = 'Ei kelvollinen sivusto';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Ei voimassa syntymäpäivä';
$_COS_LANG_MODULE['You are not that old'] = 'Et ole, että vanhat';
$_COS_LANG_MODULE['Edit your profile information'] = 'Muokkaa profiilia tiedot';
$_COS_LANG_MODULE['Your website'] = 'Sivustosi';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Sinun syntymäpäivä. Muoto on vvvv-kk-pp';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Kirjoita muutama sana itsestäsi';
$_COS_LANG_MODULE['Update'] = 'Päivitys';
