<?php

$_COS_LANG_MODULE['You are logged in using email: '] = 'Du är inloggad via e-post:';
$_COS_LANG_MODULE['Your screenname is not set yet'] = 'Din screen är inte inställd ännu';
$_COS_LANG_MODULE['Your screenname is: '] = 'Din screen är:';
$_COS_LANG_MODULE['Logout'] = 'Logga ut';
$_COS_LANG_MODULE['Submitted by: '] = 'Inskickat av:';
$_COS_LANG_MODULE['User'] = 'Användare';
$_COS_LANG_MODULE['Profile page '] = 'Profilsida';
$_COS_LANG_MODULE['This is your profile.'] = 'Detta är din profil.';
$_COS_LANG_MODULE['No bio yet'] = 'Ingen bio ännu';
$_COS_LANG_MODULE['Your profile'] = 'Din profil';
$_COS_LANG_MODULE['Your profile is empty!'] = 'Din profil är tom!';
$_COS_LANG_MODULE['Screen name'] = 'Signaturen';
$_COS_LANG_MODULE['Website'] = 'Webbplats';
$_COS_LANG_MODULE['No website'] = 'Ingen webbplats';
$_COS_LANG_MODULE['Unknown'] = 'Okänd';
$_COS_LANG_MODULE['Age'] = 'Ålder';
$_COS_LANG_MODULE['Your profile has been updated'] = 'Din profil har uppdaterats';
$_COS_LANG_MODULE['Not a valid website'] = 'Inte en godkänd webbplats';
$_COS_LANG_MODULE['Not a valid birthday'] = 'Inte en giltig födelsedag';
$_COS_LANG_MODULE['You are not that old'] = 'Du är inte så gammal';
$_COS_LANG_MODULE['Edit your profile information'] = 'Redigera din profilinformation';
$_COS_LANG_MODULE['Your website'] = 'Din webbplats';
$_COS_LANG_MODULE['Your birthday. Format is yyyy-mm-dd'] = 'Din födelsedag. Format är åååå-mm-dd';
$_COS_LANG_MODULE['Write a few words about yourself'] = 'Skriv några ord om dig själv';
$_COS_LANG_MODULE['Update'] = 'Uppdatera';
